version: "3.3"

services:
  db:
    image: postgres:16.1-alpine3.19
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  backend:
    restart: always
    build:
      context: ./backend/
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/:/app/
    depends_on:
      - db

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
      - 443:443
    volumes:
      - static:/static/
      - media:/media/
      - certs:/etc/letsencrypt

volumes:
  postgres_data:
  static:
  media:
  certs:
