# Generated by Django 4.2.11 on 2024-03-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_dependence_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='from_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_forms', to='forms.form'),
        ),
    ]
