# Generated by Django 4.2.11 on 2024-03-19 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_form_from_form"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dependence",
            options={
                "ordering": ("id",),
                "verbose_name": "Зависимость",
                "verbose_name_plural": "Зависимости",
            },
        ),
        migrations.AlterModelOptions(
            name="form",
            options={
                "ordering": ("-id",),
                "verbose_name": "Форма для заполнения",
                "verbose_name_plural": "Формы для заполнения",
            },
        ),
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ("id",),
                "verbose_name": "Опция",
                "verbose_name_plural": "Опции",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("id",),
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.RemoveField(
            model_name="form",
            name="from_form",
        ),
        migrations.AddField(
            model_name="form",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FilledForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_forms",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заполненная форма",
                "verbose_name_plural": "Заполенные формы",
                "ordering": ("-id",),
            },
        ),
    ]
