# Generated by Django 4.2.11 on 2024-03-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_alter_dependence_options_alter_form_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="checked",
        ),
        migrations.CreateModel(
            name="FilledQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Short answer", "Short"),
                            ("Paragraph", "Long"),
                            ("Date", "Date"),
                            ("Time", "Time"),
                            ("Checkboxes", "Checkboxes"),
                            ("Multiple choice", "Multiple"),
                            ("Drop-down", "Dropdown"),
                        ]
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="forms.filledform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FilledOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField()),
                ("checked", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.filledquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция",
                "verbose_name_plural": "Опции",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
